# Generated by Django 4.2.2 on 2024-02-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_image_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='UserImage/default.jpg', null=True, upload_to='UserImage', verbose_name='Image'),
        ),
    ]
