# Generated by Django 4.2.2 on 2023-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=20, verbose_name='Full_name')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('subject', models.CharField(max_length=20, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Text')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone Num')),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contacts us',
            },
        ),
    ]
