# Generated by Django 4.2.2 on 2023-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_belowbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='belowbanner',
            name='icon',
            field=models.ImageField(null=True, upload_to='BelowIcons', verbose_name='Below icons'),
        ),
    ]
