# Generated by Django 4.2.2 on 2023-07-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_belowbanner_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BelowBanner',
        ),
    ]
