# Generated by Django 4.2.2 on 2023-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_belowbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('phone_num', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('facebook', models.URLField()),
                ('youtube', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
