# Generated by Django 4.2.2 on 2023-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
