# Generated by Django 4.2.2 on 2023-07-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_newsletter_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'News Letter', 'verbose_name_plural': 'News Letters'},
        ),
    ]
