# Generated by Django 4.2.2 on 2024-02-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_newsletter_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
