# Generated by Django 4.2.2 on 2023-06-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=10, verbose_name='Size'),
        ),
    ]
