# Generated by Django 4.2.2 on 2023-06-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=models.CharField(choices=[('USD', '$'), ('AZN', '₼'), ('EUR', '€')], max_length=10, verbose_name='Price_currency'),
        ),
    ]
