# Generated by Django 4.2.2 on 2023-06-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=models.CharField(choices=[('$', 'USD'), ('₼', 'AZN'), ('€', 'EUR')], max_length=10, verbose_name='Price_currency'),
        ),
    ]
