# Generated by Django 4.2.2 on 2023-06-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_caregorypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_p', to='product.category')),
            ],
            options={
                'verbose_name': 'Category Point',
                'verbose_name_plural': 'Category Points',
            },
        ),
        migrations.DeleteModel(
            name='CaregoryPoint',
        ),
    ]
