# Generated by Django 4.2.2 on 2023-06-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_product_sub_category_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='Category_Image', verbose_name='Image'),
        ),
    ]
