# Generated by Django 4.2.2 on 2023-07-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_product_category_alter_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
