# Generated by Django 4.2.2 on 2023-07-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Price'),
        ),
    ]
