# Generated by Django 4.2.2 on 2023-07-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
