# Generated by Django 4.2.2 on 2023-07-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_product_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Brown', 'Brown'), ('Pink', 'Pink'), ('White', 'White'), ('Black', 'Black'), ('Grey', 'Grey')], null=True, verbose_name='Color'),
        ),
    ]
