# Generated by Django 4.2.2 on 2023-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Brown', 'Brown'), ('Pink', 'Pink'), ('White', 'White'), ('Black', 'Black')], null=True, verbose_name='Color'),
        ),
    ]
