# Generated by Django 4.2.2 on 2024-02-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_productreviews_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscrabed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Subscraber',
                'verbose_name_plural': 'Subscrabers',
            },
        ),
    ]
