# Generated by Django 4.2.2 on 2024-02-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_product_description_en_product_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, default='Categoties', max_length=50, verbose_name='Title'),
        ),
    ]
