# Generated by Django 4.2.2 on 2024-02-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
