# Generated by Django 4.2.2 on 2024-02-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name English'),
        ),
    ]
