# Generated by Django 4.2.2 on 2023-06-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], max_length=10, null=True, verbose_name='Status'),
        ),
    ]
