# Generated by Django 4.2.2 on 2023-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=10, null=True, verbose_name='Size'),
        ),
    ]
