# Generated by Django 4.2.2 on 2023-07-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
