# Generated by Django 4.2.2 on 2023-07-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_qty',
        ),
    ]
