# Generated by Django 4.2.2 on 2023-07-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
