# Generated by Django 4.2.2 on 2023-07-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Brown', 'Brown'), ('Pink', 'Pink'), ('White', 'White'), ('Black', 'Black'), ('Grey', 'Grey')], max_length=20, null=True, verbose_name='Color'),
        ),
    ]
