# Generated by Django 4.2.2 on 2023-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Brown', 'Brown'), ('Pink', 'Pink'), ('White', 'White'), ('Black', 'Black')], max_length=20, null=True, verbose_name='Color'),
        ),
    ]
