# Generated by Django 4.2.2 on 2023-07-15 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_product_color'),
        ('order', '0018_checkoutitem_status_alter_order_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.product'),
        ),
    ]
