# Generated by Django 4.2.2 on 2023-07-15 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_product_color'),
        ('order', '0019_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('BASKET', 'BASKET'), ('DONE', 'Done')], default='PENDING', max_length=150),
        ),
        migrations.AlterField(
            model_name='checkoutitem',
            name='status',
            field=models.CharField(choices=[('BASKET', 'BASKET'), ('DONE', 'Done')], max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('BASKET', 'BASKET'), ('DONE', 'Done')], default='BASKET', max_length=10, verbose_name='Status'),
        ),
    ]
