# Generated by Django 4.2.2 on 2024-01-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_checkoutitem_color_checkoutitem_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Basket item', 'verbose_name_plural': 'Basket items'},
        ),
        migrations.AlterField(
            model_name='checkout',
            name='address2',
            field=models.TextField(null=True),
        ),
    ]
