# Generated by Django 4.2.2 on 2024-01-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_options_alter_checkout_address2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
