# Generated by Django 4.2.2 on 2024-02-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_checkout_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('BASKET', 'Created'), ('PAYED', 'Payed'), ('ON_WAY', 'On Way'), ('DONE', 'Delivered')], default='PENDING', max_length=150),
        ),
        migrations.AlterField(
            model_name='checkoutitem',
            name='status',
            field=models.CharField(choices=[('BASKET', 'Created'), ('PAYED', 'Payed'), ('ON_WAY', 'On Way'), ('DONE', 'Delivered')], max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('BASKET', 'Created'), ('PAYED', 'Payed'), ('ON_WAY', 'On Way'), ('DONE', 'Delivered')], default='BASKET', max_length=10, verbose_name='Status'),
        ),
    ]
