# Generated by Django 4.2.2 on 2024-03-01 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0024_alter_checkout_status_alter_checkoutitem_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=150)),
                ('address1', models.TextField()),
                ('address2', models.TextField(null=True)),
                ('country', models.CharField(default='USA', max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
                ('basket_history', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('BASKET', 'Created'), ('PAYED', 'Payed'), ('ON_WAY', 'On Way'), ('DONE', 'Delivered')], default='BASKET', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Created Order',
                'verbose_name_plural': 'Created Orders',
            },
        ),
    ]
