# Generated by Django 4.2.2 on 2024-03-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_ordercreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCreate',
        ),
    ]
